LDLIBS=-lOpenCL -pthread -lm
#LDLIBS=-framework OpenCL

TARGETS= sorting mergesorting sorting_sliding sorting_hybrid sorting_hybrid_thread sorting_hybrid_thread_v2 sorting_hybrid_notlmem sorting_hybrid_counting sorting_hybrid_counting_lmem sorting_hybrid_counting_vect
TARGETS+= sorting_hybrid_counting_vectlmem simplesort sorting_counting_parallel_merge_no_repetition


all: $(TARGETS)

