LDLIBS=-lOpenCL
#LDLIBS=-framework OpenCL

TARGETS = parallelizzo
TARGETS+= vecsmoothmio vecsmoothvect vecsmooth_v4 vecsmoothvectlmem
TARGETS+= transpose transpose_lmem_vect transpose_img transpose_img_vect transpose_img_lmem
TARGETS+= reduce2 reduce4 reduce4x4 reduce4x4mod
TARGETS+= sorting mergesorting sorting_sliding sorting_hybrid
TARGETS+= scan1


all: $(TARGETS)

